<a href="https://colab.research.google.com/github/SamShinwari/Linear-Algebra-for-AI/blob/main/Assignment_on_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment Solutions

### 1. Explain the difference between a scalar, vector, matrix, and tensor with examples.

#### Scalar
A scalar is a single numerical value, a 0-dimensional array. It has magnitude but no direction.

**Example:** The number 5, representing temperature.


In [1]:
import numpy as np

scalar = np.array(5)
print(f"Scalar: {scalar}")
print(f"Dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

Scalar: 5
Dimensions: 0
Shape: ()


#### Vector
A vector is an array of numbers, representing a 1-dimensional array. It has both magnitude and direction.

**Example:** `[1, 2, 3]`, representing a point in 3D space.


In [2]:
vector = np.array([1, 2, 3])
print(f"Vector: {vector}")
print(f"Dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

Vector: [1 2 3]
Dimensions: 1
Shape: (3,)


#### Matrix
A matrix is a 2-dimensional array of numbers, organized in rows and columns.

**Example:** `[[1, 2], [3, 4]]`, representing a system of linear equations or image data.


In [3]:
matrix = np.array([[1, 2], [3, 4]])
print(f"Matrix:\n{matrix}")
print(f"Dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

Matrix:
[[1 2]
 [3 4]]
Dimensions: 2
Shape: (2, 2)


#### Tensor
A tensor is a generalization of scalars, vectors, and matrices to an arbitrary number of dimensions (or axes). It can be 3-dimensional or higher.

**Example:** An RGB image, which can be represented as a 3D array (height, width, color channels).


In [4]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"Tensor:\n{tensor}")
print(f"Dimensions: {tensor.ndim}")
print(f"Shape: {tensor.shape}")

Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions: 3
Shape: (2, 2, 3)


### 2. Create a 4 × 4 identity matrix.

In [5]:
identity_matrix = np.eye(4)
print(f"4x4 Identity Matrix:\n{identity_matrix}")

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 3. Generate a 5 × 5 random matrix.

In [6]:
random_matrix = np.random.rand(5, 5)
print(f"5x5 Random Matrix:\n{random_matrix}")

5x5 Random Matrix:
[[0.31961891 0.09697936 0.67006276 0.03081488 0.21036795]
 [0.55753609 0.81738711 0.83201915 0.17138475 0.72607856]
 [0.11410262 0.06116586 0.14151175 0.52981741 0.02994856]
 [0.72761559 0.07337843 0.73686164 0.5865972  0.18659723]
 [0.29855663 0.99868661 0.80409871 0.76519803 0.09389155]]


### 4. Create a student marks matrix for 5 students and 4 subjects.

In [7]:
marks_matrix = np.array([
    [85, 90, 78, 92], # Student 1
    [70, 65, 88, 75], # Student 2
    [95, 80, 91, 89], # Student 3
    [60, 72, 68, 80], # Student 4
    [78, 85, 70, 82]  # Student 5
])
print(f"Student Marks Matrix (5 students, 4 subjects):\n{marks_matrix}")

Student Marks Matrix (5 students, 4 subjects):
[[85 90 78 92]
 [70 65 88 75]
 [95 80 91 89]
 [60 72 68 80]
 [78 85 70 82]]


### 5. Find the shape, dimensions, and total number of elements in the marks matrix.

In [8]:
print(f"Shape of marks matrix: {marks_matrix.shape}")
print(f"Dimensions of marks matrix: {marks_matrix.ndim}")
print(f"Total number of elements in marks matrix: {marks_matrix.size}")

Shape of marks matrix: (5, 4)
Dimensions of marks matrix: 2
Total number of elements in marks matrix: 20


### 6. Extract the marks of the third student.

In [9]:
third_student_marks = marks_matrix[2, :]
print(f"Marks of the third student: {third_student_marks}")

Marks of the third student: [95 80 91 89]


### 7. Extract all marks for the second subject.

In [10]:
second_subject_marks = marks_matrix[:, 1]
print(f"Marks for the second subject: {second_subject_marks}")

Marks for the second subject: [90 65 80 72 85]


### 8. Reshape a vector of 12 elements into a 3 × 4 matrix.

In [11]:
vector_12_elements = np.arange(1, 13)
print(f"Original vector: {vector_12_elements}")

reshaped_matrix = vector_12_elements.reshape(3, 4)
print(f"Reshaped 3x4 matrix:\n{reshaped_matrix}")

Original vector: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
