<a href="https://colab.research.google.com/github/SamShinwari/Linear-Algebra-for-AI/blob/main/Lecture2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(f"Matrix:\n {A}")

Matrix:
 [[1 2]
 [3 4]]


In [8]:
print(f"Dimension: {A.ndim}")
print(f"Shape: {A.shape}")
print(f"Size: {A.size}")
print(f"Data type: {A.dtype}")

Dimension: 2
Shape: (2, 2)
Size: 4
Data type: int64


## NumPy Basics

NumPy (Numerical Python) is a powerful library for numerical operations in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. It's a fundamental package for scientific computing with Python.

### Creating Arrays

NumPy arrays can be created from Python lists or tuples. You can create 1D, 2D, or N-dimensional arrays.

In [9]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])

print(f"1D Array: {a}")
print(f"2D Array:\n {b}")

1D Array: [1 2 3]
2D Array:
 [[1 2]
 [3 4]]


### Checking Shape

The `shape` attribute returns a tuple of integers indicating the size of the array in each dimension. For a 1D array, it returns a tuple with one element. For a 2D array, it returns `(rows, columns)`.

In [10]:
print(f"Shape of 1D array (a): {a.shape}")
print(f"Shape of 2D array (b): {b.shape}")

Shape of 1D array (a): (3,)
Shape of 2D array (b): (2, 2)


### Array Dimensions

The `ndim` attribute returns the number of dimensions of the array. A 1D array has `ndim = 1`, a 2D array has `ndim = 2`, and so on.

In [11]:
print(f"Dimensions of 1D array (a): {a.ndim}")
print(f"Dimensions of 2D array (b): {b.ndim}")

Dimensions of 1D array (a): 1
Dimensions of 2D array (b): 2


### Size

The `size` attribute returns the total number of elements in the array.

In [12]:
print(f"Total elements in array (b): {b.size}")

Total elements in array (b): 4


### Data Type

The `dtype` attribute returns the data type of the elements in the array. NumPy automatically infers the data type during array creation, but you can also specify it explicitly.

In [13]:
print(f"Data type of elements in array (b): {b.dtype}")

Data type of elements in array (b): int64


### Creating Special Arrays

NumPy provides functions to create arrays with pre-filled content, such as arrays of zeros, ones, or identity matrices.

In [14]:
print(f"Zeros array (3x3):\n {np.zeros((3,3))}")
print(f"Ones array (2x4):\n {np.ones((2,4))}")
print(f"Identity matrix (4x4):\n {np.eye(4)}")
print(f"Random array (3x3):\n {np.random.rand(3,3)}")

Zeros array (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones array (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random array (3x3):
 [[0.21248082 0.43959108 0.79935696]
 [0.4045649  0.12254759 0.4205256 ]
 [0.46395215 0.55511716 0.17510481]]


### Indexing

You can access individual elements of a NumPy array using indexing, similar to Python lists. For multi-dimensional arrays, you use a comma-separated tuple of indices `[row, column]`.

In [15]:
A_idx = np.array([[5,6,7],
              [8,9,10]])

print(f"Original array A_idx:\n {A_idx}")
print(f"Element at (0,1): {A_idx[0,1]}")

Original array A_idx:
 [[ 5  6  7]
 [ 8  9 10]]
Element at (0,1): 6


### Slicing

Slicing allows you to extract sub-arrays. You can specify a range of indices using the colon operator `:`. For multi-dimensional arrays, you can slice along each dimension.

In [16]:
print(f"Original array A_idx:\n {A_idx}")
print(f"Second column of A_idx: {A_idx[:,1]}")

Original array A_idx:
 [[ 5  6  7]
 [ 8  9 10]]
Second column of A_idx: [6 9]


### Reshaping

The `reshape()` method allows you to change the shape of an array without changing its data. The new shape must have the same total number of elements as the original array.

In [17]:
A_res = np.arange(12)
print(f"Original 1D array A_res: {A_res}")
print(f"Reshaped A_res to (3,4):\n {A_res.reshape(3,4)}")

Original 1D array A_res: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped A_res to (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Flatten

The `flatten()` method returns a copy of the array collapsed into one dimension.

In [18]:
B_flat = np.array([[1,2],[3,4]])
print(f"Original 2D array B_flat:\n {B_flat}")
print(f"Flattened B_flat: {B_flat.flatten()}")

Original 2D array B_flat:
 [[1 2]
 [3 4]]
Flattened B_flat: [1 2 3 4]


In [28]:
B = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"Original 3D array B:\n {B}")

Original 3D array B:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
B.ndim

3

In [30]:
B.shape

(2, 2, 3)

In [31]:
B.size

12