<a href="https://colab.research.google.com/github/SamShinwari/Linear-Algebra-for-AI/blob/main/Lecture1_Scalar_Vector_Matrix_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is a Scalar?

A inear algebra, a scalar is a single numerical value that scales, or stretches, a vector. It can be a real number, a complex number, or an element from any field. Unlike vectors, which have both magnitude and direction, scalars only possess magnitude.

### Examples:

*   **5**: A real number, used to scale a vector to be 5 times its original length.
*   **-3**: A real number, used to scale a vector to be 3 times its original length in the opposite direction.
*   **2.5**: A decimal number.
*   **π (pi)**: A mathematical constant.

### Applications in Machine Learning and Data Science:

Scalars are fundamental in various applications:

*   **Learning Rate**: In optimization algorithms (e.g., gradient descent), the learning rate is a scalar that determines the step size taken in the direction of the negative gradient during each iteration. A larger learning rate can lead to faster convergence but might overshoot the minimum, while a smaller one can be slow but more precise.
*   **Bias**: In neural networks, bias is a scalar added to the weighted sum of inputs before activation. It allows the activation function to be shifted, providing more flexibility to the model.
*   **Loss Value**: The loss function computes a scalar value that quantifies the error of a model's predictions. The goal of training is to minimize this scalar loss value.
*   **Accuracy**: A common performance metric, accuracy is a scalar (a percentage or a fraction) indicating the proportion of correct predictions made by a classification model.
*   **Weights in a Neural Network**: While often organized into matrices, individual weights connecting neurons are scalar values.
*   **Normalization Constants**: When normalizing data, scalar constants (like standard deviation or maximum value) are used to scale features.

### Geometric Interpretation of a Scalar

Geometrically, a scalar acts on a vector by changing its magnitude (length) and potentially its direction. This operation is called **scalar multiplication**.

Let's consider a vector $\mathbf{v}$ in a 2D or 3D space.

*   **Scaling the Magnitude**: If you multiply a vector $\mathbf{v}$ by a positive scalar $c > 0$, the resulting vector $c\mathbf{v}$ will point in the same direction as $\mathbf{v}$ but will have a length $c$ times the length of $\mathbf{v}$.
    *   For example, if $c=2$, the vector $2\mathbf{v}$ is twice as long as $\mathbf{v}$.
    *   If $c=0.5$, the vector $0.5\mathbf{v}$ is half as long as $\mathbf{v}$.

*   **Changing the Direction (Reflection)**: If you multiply a vector $\mathbf{v}$ by a negative scalar $c < 0$, the resulting vector $c\mathbf{v}$ will point in the opposite direction to $\mathbf{v}$ and will have a length $|c|$ times the length of $\mathbf{v}$.
    *   For example, if $c=-1$, the vector $-\mathbf{v}$ has the same length as $\mathbf{v}$ but points in the exact opposite direction.
    *   If $c=-2$, the vector $-2\mathbf{v}$ is twice as long as $\mathbf{v}$ and points in the opposite direction.

*   **Zero Scalar**: If you multiply a vector $\mathbf{v}$ by the scalar $0$, the result is the zero vector, which has no magnitude and no specific direction, effectively collapsing the vector to a point at the origin.

In essence, scalars allow us to extend, shrink, or reverse the orientation of vectors without altering the fundamental 'line' or 'direction' along which the vector lies (unless the scalar is negative, which reverses it).

In [1]:
age = 25
temperature = 36.5

print(age)
print(temperature)

25
36.5


In [2]:
import numpy as np

# Define a vector
vector = np.array([1, 2, 3])
print(f"Original vector: {vector}")

# Define a scalar
scalar = 3
print(f"Scalar: {scalar}")

# Perform scalar multiplication
scaled_vector = scalar * vector

print(f"Scaled vector: {scaled_vector}")

Original vector: [1 2 3]
Scalar: 3
Scaled vector: [3 6 9]


## What is a Vector?

A vector is an ordered list of numbers. These numbers can represent various quantities, such as coordinates in space, features of an object, or directions and magnitudes. Unlike scalars, vectors have both magnitude (length) and direction.

### Example:

A 3-dimensional vector `v` can be represented as:

$$ \mathbf{v} = \begin{pmatrix} 2 \\ 5 \\ 7 \end{pmatrix} $$

Each number in the vector is called a component. The number of components determines the dimension of the vector (e'g., 3 components for a 3D vector).

In [3]:
import numpy as np

# Define a 3D vector
v = np.array([2, 5, 7])
print(f"Vector v: {v}")
print(f"Dimension of v: {v.shape[0]}D")

Vector v: [2 5 7]
Dimension of v: 3D


### Applications of Vectors:

Vectors are ubiquitous in various fields, especially in machine learning, data science, and physics:

*   **Word Embedding**: In Natural Language Processing (NLP), words are often converted into numerical vectors (embeddings) that capture their semantic meaning. Words with similar meanings have similar vector representations.
*   **Image Features**: Images can be represented as vectors, where each component corresponds to a pixel value or a feature extracted from the image (e.g., color histograms, edge detectors).
*   **Customer Profile**: A customer's behavior or attributes (e.g., age, income, purchase history, website visits) can be compiled into a vector for personalized recommendations or segmentation.
*   **GPS Location**: A geographical location can be represented as a vector of coordinates (e.g., latitude, longitude, and altitude).

## What is a Matrix?

A matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns. Matrices are fundamental in linear algebra and are used to represent linear transformations, systems of linear equations, and data.

### Example:

A 2x2 matrix `A` (2 rows and 2 columns) can be represented as:

$$ \mathbf{A} = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix} $$

The size of a matrix is given by the number of rows by the number of columns (e.g., 2x2, 3x5).

In [5]:
import numpy as np

# Define a 2x2 matrix
A = np.array([[1, 2],
              [3, 4]])

print(f"Matrix A:\n{A}")
print(f"Shape of Matrix A: {A.shape} (rows, columns)")

Matrix A:
[[1 2]
 [3 4]]
Shape of Matrix A: (2, 2) (rows, columns)


### Applications of Matrices in Machine Learning, Deep Learning, and Data Science:

Matrices are at the core of many computational tasks and data representations:

*   **Images**: A grayscale image can be represented as a matrix where each element corresponds to a pixel's intensity. Color images use three such matrices (one for red, green, and blue channels).
*   **Neural Network Weights**: The connections (weights) between layers in neural networks are typically represented as matrices. Matrix multiplication is used extensively during the forward and backward passes to compute activations and gradients.
*   **Dataset Representation**: Tabular datasets are often represented as matrices, where rows correspond to individual data samples (e.g., customers, observations) and columns represent features (e.g., age, income, product category).
*   **Linear Transformations**: Matrices are used to perform transformations like rotations, scaling, and shearing of vectors (e.g., in computer graphics).
*   **Covariance Matrices**: Used in statistics and machine learning to describe the variance between multiple variables in a dataset.
*   **Embedding Spaces**: Similar to word embeddings, entire datasets or complex objects can be represented as matrices in a high-dimensional space for analysis.

In [6]:
import numpy as np

# Example 1: Representing a grayscale image (e.g., a 3x3 pixel image)
# Each value represents pixel intensity (0=black, 255=white)
image_matrix = np.array([
    [255, 100, 0],
    [ 50, 150, 200],
    [  0, 200, 255]
])
print(f"\nGrayscale Image Matrix:\n{image_matrix}")
print(f"Shape: {image_matrix.shape}")

# Example 2: Neural Network Weights (e.g., weights connecting an input layer to a hidden layer)
# If input layer has 3 neurons and hidden layer has 2 neurons
weights_matrix = np.array([
    [0.1, 0.4],
    [0.2, 0.5],
    [0.3, 0.6]
])
print(f"\nNeural Network Weights Matrix:\n{weights_matrix}")
print(f"Shape: {weights_matrix.shape}")

# Example 3: Dataset representation (e.g., 3 samples, 2 features each)
# Rows are samples, columns are features (e.g., [Age, Income])
dataset_matrix = np.array([
    [25, 50000],
    [30, 65000],
    [22, 48000]
])
print(f"\nDataset Matrix (Samples x Features):\n{dataset_matrix}")
print(f"Shape: {dataset_matrix.shape}")


Grayscale Image Matrix:
[[255 100   0]
 [ 50 150 200]
 [  0 200 255]]
Shape: (3, 3)

Neural Network Weights Matrix:
[[0.1 0.4]
 [0.2 0.5]
 [0.3 0.6]]
Shape: (3, 2)

Dataset Matrix (Samples x Features):
[[   25 50000]
 [   30 65000]
 [   22 48000]]
Shape: (3, 2)


## What is a Tensor?

A tensor is a generalization of scalars, vectors, and matrices to an arbitrary number of dimensions (also known as axes or ranks).

*   **Scalar**: A 0-dimensional tensor (a single number).
*   **Vector**: A 1-dimensional tensor (an array of numbers).
*   **Matrix**: A 2-dimensional tensor (a rectangular array of numbers).
*   **Higher-Dimensional Tensors**: Tensors can have 3, 4, or more dimensions. For example, a color image can be a 3D tensor (height x width x color channels), and a video can be a 4D tensor (number of frames x height x width x color channels).

### Examples:

*   **Scalar** → 0D (e.g., `5`, `learning_rate`)
*   **Vector** → 1D (e.g., `[2, 5, 7]`, `word_embedding`)
*   **Matrix** → 2D (e.g., `[[1, 2], [3, 4]]`, `image_pixels`)
*   **Color Image** → 3D (e.g., `(height, width, color_channels)`)
*   **Video** → 4D (e.g., `(frames, height, width, color_channels)`)
*   **Large Language Models** → Often deal with multi-dimensional tensors representing batches of sequences of word embeddings, attention scores, etc.

## Dimensions and Shapes

The **dimension** (or rank) of a tensor refers to the number of indices required to access an element. The **shape** describes the size of each dimension.

### Example:

Consider a matrix `A`:

$$ \mathbf{A} = \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{pmatrix} $$

*   **Shape**: `(2, 3)`
    *   Meaning: It has 2 rows and 3 columns.
    *   This is a 2-dimensional tensor (a matrix).

## Real AI Examples using Tensors

### Dataset Representation

Datasets in machine learning are commonly stored as tensors (often 2D matrices).

**Example: Customer Data**

| Age | Salary | Purchased |
|-----|--------|-----------|
| 25  | 50000  | 1         |
| 30  | 60000  | 0         |
| 35  | 70000  | 1         |

This tabular data can be directly represented as a 2D NumPy array (a matrix), where each row is a customer and each column is a feature. The `Purchased` column could be the target variable.

In [4]:
import numpy as np

# Example 1: 2D vector representing a point in a plane
point_2d = np.array([3.14, -2.71])
print(f"\n2D Point Vector: {point_2d}")

# Example 2: Vector representing RGB color values for a pixel
rgb_color = np.array([255, 128, 0]) # Red, Green, Blue components
print(f"RGB Color Vector: {rgb_color}")

# Example 3: Feature vector for a machine learning model (e.g., customer profile)
# [Age, Income, Number_of_purchases, Has_premium_subscription]
customer_features = np.array([35, 75000, 12, 1])
print(f"Customer Feature Vector: {customer_features}")


2D Point Vector: [ 3.14 -2.71]
RGB Color Vector: [255 128   0]
Customer Feature Vector: [   35 75000    12     1]


In [7]:
import numpy as np

# 5. Tensor Example
tensor = np.random.rand(3,4,5)
print(f"\nTensor generated by np.random.rand(3,4,5):\n{tensor}")
print(f"Shape of the tensor: {tensor.shape}")

# 6. Dimensions and Shapes - Matrix Example
A = np.array([[
    1,2,3],
    [4,5,6]
])
print(f"\nMatrix A for Dimensions and Shapes example:\n{A}")
print(f"Shape of Matrix A: {A.shape}")

# 7. Real AI Examples - Dataset representation
data = np.array([
    [25,50000,1],
    [30,60000,0],
    [35,70000,1]
])
print(f"\nDataset for Real AI Examples:\n{data}")
print(f"Shape of the dataset: {data.shape}")


Tensor generated by np.random.rand(3,4,5):
[[[0.6000944  0.80813545 0.54107209 0.10112606 0.90591058]
  [0.72365167 0.21128118 0.95169682 0.00897679 0.74437923]
  [0.12712908 0.78897537 0.28504161 0.85267755 0.15063848]
  [0.05894393 0.0604918  0.07930472 0.97694035 0.47398683]]

 [[0.46301759 0.89930391 0.40174456 0.18753649 0.32439668]
  [0.78667096 0.82802045 0.07539582 0.84387424 0.52300653]
  [0.52884965 0.23787146 0.4898965  0.09105025 0.08162307]
  [0.16109881 0.68081926 0.14388234 0.27496337 0.57770408]]

 [[0.64774455 0.39142505 0.13341898 0.24253533 0.30208416]
  [0.01117791 0.71554591 0.07167785 0.95261066 0.41977591]
  [0.4158315  0.76989624 0.58132021 0.09140853 0.73600022]
  [0.6462729  0.01512118 0.85836093 0.22154858 0.69216433]]]
Shape of the tensor: (3, 4, 5)

Matrix A for Dimensions and Shapes example:
[[1 2 3]
 [4 5 6]]
Shape of Matrix A: (2, 3)

Dataset for Real AI Examples:
[[   25 50000     1]
 [   30 60000     0]
 [   35 70000     1]]
Shape of the dataset: (3, 