<a href="https://colab.research.google.com/github/SamShinwari/Linear-Algebra-for-AI/blob/main/Linear_Dependence_Independence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Example 1: Independent Vectors

In [5]:
import numpy as np

A = np.array([
    [1, 0],
    [0, 1]
])

rank = np.linalg.matrix_rank(A)

print("Rank:", rank)

if rank == A.shape[1]:
    print("Vectors are Linearly Independent")
else:
    print("Vectors are Linearly Dependent")

Rank: 2
Vectors are Linearly Independent


##Example 2: Dependent Vectors

In [6]:
import numpy as np

A = np.array([
    [1, 2],
    [2, 4]
])

rank = np.linalg.matrix_rank(A)

print("Rank:", rank)

if rank == A.shape[1]:
    print("Vectors are Linearly Independent")
else:
    print("Vectors are Linearly Dependent")

Rank: 1
Vectors are Linearly Dependent


## Real AI Example

Suppose a dataset contains these features:

Height	Weight	Weight × 2
170	70	140
180	80	160
160	60	120

The third feature is exactly twice the second.

These features are linearly dependent because one can be computed from another.

In practice, removing redundant features can simplify models and sometimes improve training efficiency.

In [7]:
import numpy as np

A_example = np.array([
    [170, 70, 140],
    [180, 80, 160],
    [160, 60, 120]
])

rank_example = np.linalg.matrix_rank(A_example)

print("Matrix A (features):")
print(A_example)
print("Rank:", rank_example)

if rank_example == A_example.shape[1]:
    print("Columns (features) are Linearly Independent")
else:
    print("Columns (features) are Linearly Dependent")

Matrix A (features):
[[170  70 140]
 [180  80 160]
 [160  60 120]]
Rank: 2
Columns (features) are Linearly Dependent
