<a href="https://colab.research.google.com/github/SamShinwari/Linear-Algebra-for-AI/blob/main/Matrix_Operations_Programming_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Programming Lab: Matrix Operations

### Matrix Multiplication using NumPy

In [1]:
import numpy as np

# Define two matrices
A = np.array([[2, 1], [3, 4]])
B = np.array([[1, 5], [2, 6]])

# Matrix multiplication using @ operator
C_np_at = A @ B
print("Matrix multiplication using @ operator:")
display(C_np_at)

# Matrix multiplication using np.dot()
C_np_dot = np.dot(A, B)
print("\nMatrix multiplication using np.dot():")
display(C_np_dot)

Matrix multiplication using @ operator:


array([[ 4, 16],
       [11, 39]])


Matrix multiplication using np.dot():


array([[ 4, 16],
       [11, 39]])

### Matrix Multiplication without NumPy (Nested Loops)

In [2]:
def multiply_matrices_manual(A, B):
    # Get dimensions
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])

    # Check if multiplication is possible
    if cols_A != rows_B:
        raise ValueError("Number of columns in first matrix must equal number of rows in second matrix")

    # Initialize result matrix with zeros
    C = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

    # Perform multiplication
    for i in range(rows_A):  # Iterate through rows of A
        for j in range(cols_B):  # Iterate through columns of B
            for k in range(cols_A):  # Iterate through columns of A (or rows of B)
                C[i][j] += A[i][k] * B[k][j]
    return C

# Example usage with lists of lists
A_manual = [[2, 1], [3, 4]]
B_manual = [[1, 5], [2, 6]]

C_manual = multiply_matrices_manual(A_manual, B_manual)
print("Matrix multiplication without NumPy:")
display(C_manual)

Matrix multiplication without NumPy:


[[4, 16], [11, 39]]

### Matrix Transpose

In [3]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix:")
display(matrix)

# Transpose using NumPy
transposed_np = matrix.T
print("\nTransposed Matrix (NumPy):")
display(transposed_np)

# Manual Transpose function
def transpose_manual(matrix_list):
    rows = len(matrix_list)
    cols = len(matrix_list[0])
    transposed = [[0 for _ in range(rows)] for _ in range(cols)]
    for i in range(rows):
        for j in range(cols):
            transposed[j][i] = matrix_list[i][j]
    return transposed

matrix_list_manual = [[1, 2, 3], [4, 5, 6]]
transposed_manual = transpose_manual(matrix_list_manual)
print("\nTransposed Matrix (Manual):")
display(transposed_manual)

Original Matrix:


array([[1, 2, 3],
       [4, 5, 6]])


Transposed Matrix (NumPy):


array([[1, 4],
       [2, 5],
       [3, 6]])


Transposed Matrix (Manual):


[[1, 4], [2, 5], [3, 6]]

### Identity Matrix

In [4]:
import numpy as np

# Identity matrix using NumPy
identity_np = np.eye(3) # 3x3 identity matrix
print("3x3 Identity Matrix (NumPy):")
display(identity_np)

# Manual Identity Matrix function
def create_identity_manual(size):
    identity_matrix = [[0 for _ in range(size)] for _ in range(size)]
    for i in range(size):
        identity_matrix[i][i] = 1
    return identity_matrix

identity_manual = create_identity_manual(3)
print("\n3x3 Identity Matrix (Manual):")
display(identity_manual)

3x3 Identity Matrix (NumPy):


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


3x3 Identity Matrix (Manual):


[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

### Check if a Matrix is Symmetric

In [5]:
import numpy as np

def is_symmetric(matrix):
    # Convert to NumPy array for easier comparison, if not already
    matrix_np = np.array(matrix)
    return np.array_equal(matrix_np, matrix_np.T)

# Symmetric matrix example
Symmetric_matrix = [[1, 2, 3], [2, 4, 5], [3, 5, 6]]
print("Matrix 1:")
display(Symmetric_matrix)
print(f"Is Matrix 1 symmetric? {is_symmetric(Symmetric_matrix)}")

# Non-symmetric matrix example
Non_symmetric_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("\nMatrix 2:")
display(Non_symmetric_matrix)
print(f"Is Matrix 2 symmetric? {is_symmetric(Non_symmetric_matrix)}")

Matrix 1:


[[1, 2, 3], [2, 4, 5], [3, 5, 6]]

Is Matrix 1 symmetric? True

Matrix 2:


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Is Matrix 2 symmetric? False


### Create Diagonal and Triangular Matrices

In [6]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Matrix:")
display(matrix)

# Diagonal matrix (extracts diagonal elements)
diagonal_elements = np.diag(matrix)
print("\nDiagonal elements (np.diag(matrix)):")
display(diagonal_elements)

# Create a diagonal matrix from a 1D array
diagonal_matrix_from_array = np.diag([10, 20, 30])
print("\nDiagonal matrix from array (np.diag([10, 20, 30])):")
display(diagonal_matrix_from_array)

# Upper triangular matrix
upper_triangular = np.triu(matrix)
print("\nUpper Triangular Matrix:")
display(upper_triangular)

# Lower triangular matrix
lower_triangular = np.tril(matrix)
print("\nLower Triangular Matrix:")
display(lower_triangular)

Original Matrix:


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


Diagonal elements (np.diag(matrix)):


array([1, 5, 9])


Diagonal matrix from array (np.diag([10, 20, 30])):


array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])


Upper Triangular Matrix:


array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])


Lower Triangular Matrix:


array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

## Mini Project: Create a Simple Neural Network Forward Pass

In [7]:
import numpy as np

# 1. Define an input matrix (e.g., batch of 2 samples, 3 features each)
X = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])
print("Input Matrix X:")
display(X)

# 2. Define a weight matrix (e.g., 3 input features, 4 neurons in the layer)
W = np.array([[0.1, 0.2, 0.3, 0.4],
              [0.5, 0.6, 0.7, 0.8],
              [0.9, 0.0, 0.1, 0.2]])
print("\nWeight Matrix W:")
display(W)

# 3. Multiply them (XW)
# Output of this linear transformation, before bias and activation
Z = X @ W
print("\nResult of X @ W (before bias and activation):")
display(Z)

# 4. Add a bias vector (e.g., 4 biases, one for each neuron)
b = np.array([0.1, -0.2, 0.3, -0.4])
print("\nBias Vector b:")
display(b)

# Add bias to each sample in the batch
Z_biased = Z + b
print("\nResult after adding bias (Z + b):")
display(Z_biased)

# 5. Apply the ReLU activation function
# ReLU(x) = max(0, x)
def relu(x):
    return np.maximum(0, x)

A = relu(Z_biased)
print("\nOutput after ReLU activation:")
display(A)

print("\nThis demonstrates a single layer's forward pass in a neural network.")

Input Matrix X:


array([[1., 2., 3.],
       [4., 5., 6.]])


Weight Matrix W:


array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 0. , 0.1, 0.2]])


Result of X @ W (before bias and activation):


array([[3.8, 1.4, 2. , 2.6],
       [8.3, 3.8, 5.3, 6.8]])


Bias Vector b:


array([ 0.1, -0.2,  0.3, -0.4])


Result after adding bias (Z + b):


array([[3.9, 1.2, 2.3, 2.2],
       [8.4, 3.6, 5.6, 6.4]])


Output after ReLU activation:


array([[3.9, 1.2, 2.3, 2.2],
       [8.4, 3.6, 5.6, 6.4]])


This demonstrates a single layer's forward pass in a neural network.


## Practice Questions

### Conceptual Questions

#### Why must the number of columns in the first matrix equal the number of rows in the second matrix for multiplication?

**Answer:** For matrix multiplication $AB = C$, where $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, the resulting matrix $C$ will be an $m \times p$ matrix. The multiplication works by taking the dot product of rows from the first matrix and columns from the second matrix.

Specifically, to compute an element $C_{ij}$, you multiply each element in row $i$ of matrix $A$ by the corresponding element in column $j$ of matrix $B$ and sum these products. This requires that the number of elements in row $i$ of $A$ (which is $n$, the number of columns in $A$) must be exactly the same as the number of elements in column $j$ of $B$ (which is $n$, the number of rows in $B$). If these numbers don't match, the dot product cannot be performed.

#### Why is matrix multiplication generally not commutative (i.e., $AB \neq BA$)?

**Answer:** Matrix multiplication is generally not commutative for several reasons:

1.  **Dimension Mismatch:** If $A$ is $m \times n$ and $B$ is $n \times p$, then $AB$ is defined. For $BA$ to be defined, $p$ must equal $m$. Even if $p=m$, the resulting dimensions will be different unless $m=n=p$. For example, if $A$ is $2 \times 3$ and $B$ is $3 \times 2$, $AB$ is $2 \times 2$ and $BA$ is $3 \times 3$.
2.  **Order of Operations:** The process of multiplying rows by columns means the elements are combined in a specific order. Changing the order ($BA$ instead of $AB$) fundamentally changes which elements are multiplied together, leading to different sums.

Only in very specific cases (e.g., if one matrix is an identity matrix, or for certain diagonal matrices) does $AB = BA$ hold.

#### What is the role of the identity matrix?

**Answer:** The identity matrix, typically denoted as $I$ (or $I_n$ for an $n \times n$ matrix), plays a role similar to the number '1' in scalar arithmetic. When an $m \times n$ matrix $A$ is multiplied by an identity matrix of appropriate size, the original matrix $A$ remains unchanged:

*   $A I_n = A$ (if $A$ is $m \times n$, $I_n$ must be $n \times n$)
*   $I_m A = A$ (if $A$ is $m \times n$, $I_m$ must be $m \times m$)

It is a square matrix with ones on the main diagonal and zeros everywhere else. Its primary role is to act as a multiplicative identity in matrix algebra, which is crucial in solving systems of linear equations, finding inverse matrices, and various transformations in linear algebra.

#### Why is the transpose operation important in machine learning?

**Answer:** The transpose operation ($A^T$) is very important in machine learning for several reasons:

1.  **Vector-Vector and Matrix-Vector Products:** It allows for correct dimension alignment for dot products (e.g., $w^T x$ in linear models, or $x^T w$ for column vectors) and matrix-vector multiplications. For instance, if $x$ is a column vector, $x^T$ is a row vector, making $x^T x$ a scalar (dot product).
2.  **Covariance Matrices:** Covariance matrices, which measure the relationship between variables, are always symmetric ($C = C^T$). The transpose is implicitly used in their definition.
3.  **Least Squares and Regression:** In linear regression, the normal equations for finding the optimal weights involve $(X^T X)^{-1} X^T y$, where $X^T X$ and $X^T y$ require transpose operations for valid matrix multiplication.
4.  **Neural Networks (Backpropagation):** The transpose is fundamental in backpropagation. When calculating gradients, weights from a previous layer are multiplied by the transpose of the error signal from the subsequent layer to propagate the error backward.
5.  **Orthogonal Matrices:** Orthogonal matrices, where $Q^T Q = Q Q^T = I$, are used in transformations that preserve magnitudes and angles (e.g., PCA, SVD), and the transpose is central to their definition.
6.  **Attention Mechanisms in Transformers:** As mentioned in the problem description, the attention scores are computed using $QK^T$, where $K^T$ is the transpose of the Key matrix, allowing the dot product between queries and keys to determine similarity.

#### What is a sparse matrix, and why is it useful in NLP?

**Answer:**

A **sparse matrix** is a matrix in which most of the elements are zero. Conversely, a matrix with a high proportion of non-zero elements is called a dense matrix.

**Why it is useful in NLP:**

1.  **High Dimensionality and Zero Counts:** In many NLP tasks, text data is represented using techniques like Bag-of-Words (BoW) or TF-IDF. These representations create very high-dimensional feature vectors (where each dimension corresponds to a word in the vocabulary). For any given document, only a small fraction of these words will actually be present, leading to many zero entries in the feature vector. When these vectors are combined into a matrix (e.g., document-term matrix), it results in a sparse matrix.
2.  **Computational Efficiency:** Storing and operating on dense matrices with many zeros is inefficient in terms of both memory and computation. Sparse matrix formats (like Compressed Sparse Row (CSR) or Coordinate (COO)) only store the non-zero elements and their indices. This drastically reduces memory usage and speeds up computations (e.g., matrix multiplication, dot products) by avoiding operations on zero values.
3.  **Feature Engineering:** Sparse matrices naturally arise from one-hot encoding categorical features or n-grams, common in NLP. Efficient handling of these sparse representations is key to building scalable NLP models.
4.  **Graph Representations:** In some NLP tasks, relationships between words or entities can be represented as graphs, where adjacency matrices can often be sparse if connections are not universal.

### Numerical Questions

Given:

$A=\begin{bmatrix} 2 & 1 \\ 3 & 4 \end{bmatrix}$, $B=\begin{bmatrix} 1 & 5 \\ 2 & 6 \end{bmatrix}$

#### Compute: $A + B$

In [8]:
import numpy as np

A = np.array([[2, 1], [3, 4]])
B = np.array([[1, 5], [2, 6]])

sum_AB = A + B
print("A + B =")
display(sum_AB)

A + B =


array([[ 3,  6],
       [ 5, 10]])

#### Compute: $A - B$

In [9]:
import numpy as np

A = np.array([[2, 1], [3, 4]])
B = np.array([[1, 5], [2, 6]])

diff_AB = A - B
print("A - B =")
display(diff_AB)

A - B =


array([[ 1, -4],
       [ 1, -2]])

#### Compute: $AB$

In [10]:
import numpy as np

A = np.array([[2, 1], [3, 4]])
B = np.array([[1, 5], [2, 6]])

prod_AB = A @ B # or np.dot(A, B)
print("A B =")
display(prod_AB)

A B =


array([[ 4, 16],
       [11, 39]])

#### Compute: $A^T$

In [11]:
import numpy as np

A = np.array([[2, 1], [3, 4]])

transpose_A = A.T
print("A^T =")
display(transpose_A)

A^T =


array([[2, 3],
       [1, 4]])

#### Verify that $AI = A$ using a $2 \times 2$ identity matrix

In [12]:
import numpy as np

A = np.array([[2, 1], [3, 4]])
I = np.eye(2) # 2x2 identity matrix

prod_AI = A @ I
print("A:")
display(A)
print("\nI (2x2 Identity Matrix):")
display(I)
print("\nAI:")
display(prod_AI)

is_equal = np.array_equal(A, prod_AI)
print(f"\nIs AI equal to A? {is_equal}")

A:


array([[2, 1],
       [3, 4]])


I (2x2 Identity Matrix):


array([[1., 0.],
       [0., 1.]])


AI:


array([[2., 1.],
       [3., 4.]])


Is AI equal to A? True
