<a href="https://colab.research.google.com/github/SamShinwari/Linear-Algebra-for-AI/blob/main/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS500 - Data Science Tools and Technique

**Dr. Bahar Ali**

**Assistant Professor (CS), National University Of Computer and Emerging Sciences, Peshawar.**

## NumPy (Numerical Python)

    NumPy stands for Numerical Python.
    It is a fundamental/ core library needed for scientific computing with Python, which adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## Remember to Install Numpy
!pip install numpy==1.5


    In the first cell we put the code to import the numpy library as np.
    This is for convenience; every time we need to use some functionality from the numpy library, we will write
    np instead of numpy.

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.5'

### The Basics

In [ ]:
a = np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [ ]:
b = np.array([
                [9.0,8.0,7.0],

                [6.0,5.0,4]
            ]

)
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get Dimension
b.ndim

2

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
a = np.array(
                [   [  [ [1,1], [2,2] ],  [ [3,3], [4,4] ]  ],

                    [  [ [5,5], [6,6] ],  [ [7,7], [8,8] ]  ]   ])

In [ ]:
print("Dimensions: ", a.ndim)
print("Shape     : ", a.shape)

Dimensions:  4
Shape     :  (2, 2, 2, 2)


In [ ]:
# Get Type
a.dtype

dtype('int64')

In [ ]:
# Get Size (Size of one value i.e. size of one value of dtype='int64' = 8)
a.itemsize

8

In [ ]:
#Get total size in bytes
a.itemsize * a.size

128

In [ ]:
# OR Get total size
a.nbytes

128

In [ ]:
# Get number of elements
a.size

16

### Accessing/ Changing specific elements

In [ ]:
a = np.array([[1, 2, 3,  4,  5,  6,  7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element
a[1, 1]

9

In [ ]:
# Get a specific row/ First value of first dimension and all values of second dimension
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column/ All values of first dimension and third value of second dimension
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
# Getting elements from reverse side
a[0, -1:1:-2]

array([7, 5, 3])

In [ ]:
a = np.array([[1, 2, 3,  4,  5,  6,  7],
              [8, 9, 10, 11, 12, 13, 14]])
a[1,5] = 20

a[:,2] = [10,50]
print(a)

[[ 1  2 10  4  5  6  7]
 [ 8  9 50 11 12 20 14]]


In [ ]:
a

array([[ 1,  2, 10,  4,  5,  6,  7],
       [ 8,  9, 50, 11, 12, 20, 14]])

3-dim example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element
b[0,1,1]

4

In [ ]:
# Replace
b[:,0,:] = [[90,90],[80,80]]
b

array([[[90, 90],
        [ 3,  4]],

       [[80, 80],
        [ 7,  8]]])

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b[:,0,:] = [[22,55],[33,44]]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[22 55]
  [ 3  4]]

 [[33 44]
  [ 7  8]]]


### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
z_mat = np.zeros((2,3))
z_mat

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1's Tensor
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
a.shape

(2, 7)

In [ ]:
# Random decimal number
np.random.rand()

0.8839726443737193

In [ ]:
# Random decimal numbers array
np.random.rand(4,2)

array([[0.99863465, 0.42415196],
       [0.69055211, 0.19306632],
       [0.90424667, 0.69253809],
       [0.89863858, 0.19280995]])

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4,  4,  4],
       [ 3,  7, -2],
       [-1,  3, -4]])

In [ ]:
#random.normal(loc=0.0, scale=1.0, size=None)
mean = 10 # mean
sigma = 2 # standard deviation
rand_norm = np.random.normal(mean, sigma, 10)
rand_norm

array([11.96951135,  6.7365561 ,  7.99111196, 11.77788806, 10.01574904,
       12.57331188,  8.66692347,  9.58836405, 10.11768385,  8.38652697])

In [ ]:
# The identity matrix
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

## In numpy axis = 1 by default.
## axis = 0 along the rows,
## axis = 1 along the columns.

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)
print("---------------")

z = np.zeros((3,3))
print(z)

print("---------------")

z[1,1] = 9
print(z)

print("---------------")

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
---------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
---------------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
---------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()         #Works in numpy array
b = a[:]             #Not working in numpy array, however, works in Python list

b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [ ]:
# Copying in Python list
a = [1,2,3]
b = a.copy()         #Works in Python list
b = a[:]             #Works in Python list

b[0] = 100
print(a)
print(b)

[1, 2, 3]
[100, 2, 3]


## Mathematics Functions

### Element-wise operations

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a * a # Element wise multiplication

array([ 1,  4,  9, 16])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take the sin and Cos
degrees = 360
# 180 degrees = np.pi radians    i.e. 3.14 radians
# 1   degree  = (np.pi/180) radians  i.e. 0.017.. radians
# 360 degrees = (np.pi/180) * degrees radians  i.e. 6.283 radians

radians = (np.pi/180) * degrees

print(radians)
np.cos(radians) # Basically the method is used for radian, that's why we need to convert degree to radians first.

6.283185307179586


1.0

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
print(c)
det_v = np.linalg.det(c)
print(det_v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [ ]:
# Find Trace (Return the sum along diagonals of the array.)
trace_val = np.trace(c)
print(trace_val)


3.0


In [ ]:
e_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
e_mat.shape

(3, 3)

In [ ]:
# Eigenvalues
np.linalg.eigvals(e_mat)

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [ ]:
ab = np.array([[1,1,3],[1,2,1],[1,1,2]])

# Inverse
np.linalg.inv(ab)

array([[-3., -1.,  5.],
       [ 1.,  1., -2.],
       [ 1., -0., -1.]])

### Statistics

In [ ]:
stats = np.array([[1,8,3],[4,5,6]])
stats

array([[1, 8, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.std(stats)

2.217355782608345

In [ ]:
np.max(stats, axis=1)

array([8, 6])

In [ ]:
np.sum(stats, axis=0)

array([ 5, 13,  9])

### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print("Shape: ", before.shape)

print("_______________\n")

after = before.reshape((4,2))
print(after)
print("Shape: ", after.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape:  (2, 4)
_______________

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape:  (4, 2)


In [ ]:
after = before.reshape((4*2))
after

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
h2

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous
### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int16')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [ ]:
~((filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
filedata[~((filedata > 50) & (filedata < 100))]

array([  1,  13,  21,  11, 196,   4,   3,  34,   6,   7,   8,   0,   1,
         2,   3,   4,   5,   3,  42,  12,  33, 766,   4,   6,   4,   3,
         4,   5,   6,   7,   0,  11,  12,   1,  22,  33,  11, 999,  11,
         2,   1,   0,   1,   2,   9,   8,   7,   1], dtype=int16)

In [ ]:
# Python way to make copy from list/dictionaly/tuple etc
#mlist = [x for x in filedata]
#mlist